config-version: 2

name: 'claires_sql_puzzlers'
version: '1.0.0'

profile: 'claires_sql_puzzlers'

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"

models:
  claires_sql_puzzlers:
    +materialized: view
