version: 2

models:
  - name: effective_subscription_changes
    description: >
      The effective dates of each subscription upgrade/downgrade. Changes are
      effective at the next billing date, and in the case of multiple changes
      within a billing period, only the last change applies.
    columns:
      - name: subscription_id
        description: The unique identifier for the subscription the change was made to.
      - name: new_price
        description: The new price of the subscription.
      - name: changed_at
        description: The date that the change was made.
      - name: effective_at
        description: The date at which the change will be effective.